parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: jx_zilp
    database_user: root
    database_password: 'root'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: zh_CN
    secret: qyjszzvk6u8gwosg8ss0g04w8w8gc88
    webpack_base_url: http://jxdl.szzlpcm.com
    user_partner: none