switch_org:
    path: /swithOrg/{id}
    defaults: { _controller: OrgBundle:Org:switchOrg }

org_tree:
    path: /org-tree.json
    defaults: { _controller: OrgBundle:Org:orgTreeJson }
    methods: [GET]